name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Tell us what you did and what happened.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this?
      placeholder: |
        1. Start the proxy...
        2. Open the dashboard...
        3. Click on...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output from the terminal.
      render: shell
  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS version, Python version, Browser.
      placeholder: e.g. Windows 11, Python 3.11, Edge 120
